function(aetherion_set_project_warnings target)
  if(MSVC)
    set(warnings /W4 /permissive- /EHsc)
    if(AETHERION_ENABLE_WARNINGS_AS_ERRORS)
      list(APPEND warnings /WX)
    endif()
  else()
    set(warnings -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion -Wshadow
                 -Wno-missing-field-initializers)
    if(AETHERION_ENABLE_WARNINGS_AS_ERRORS)
      list(APPEND warnings -Werror)
    endif()
  endif()
  target_compile_options(${target} PRIVATE ${warnings})
endfunction()
