name: ci

on:
  push:
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Configure
        run: cmake --preset ci -DAETHERION_BUILD_RENDERER=OFF
      - name: Build
        run: cmake --build --preset ci
      - name: Test
        run: ctest --preset ci
